version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REDIS_URL: ${REDIS_URL}
    environment:
      - REDIS_URL=${REDIS_URL}
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
